<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_GetItemAIManual" Id="{dff04167-7d63-4e54-ae52-95120ff519c5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_GetItemAIManual
VAR
	sFullCode		: T_MaxString;
	eCodeType		: CODE.E_CodeAI;
	stCodeInfo		: CODE.ST_CodeInfo;
	
	sF_GetItemAI	: T_MaxString;

END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Fbd"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"InitManual"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">57L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" />
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">false</v>
                      <v n="ENO">false</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">58L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">50L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"sF_GetItemAI"</v>
                            <v n="Type">"T_MaxString"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">284L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"CODE.F_GetItemAI"</v>
                        <o n="Instance" t="Operand">
                          <n n="Operand" />
                          <v n="Type">""</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">276L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems">
                            <n />
                            <n />
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"sFullCode"</v>
                              <v n="Type">"T_MaxString"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">279L</v>
                            </o>
                            <v n="Id">278L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"eCodeType"</v>
                              <v n="Type">"CODE.E_CodeAI"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">281L</v>
                            </o>
                            <v n="Id">280L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"stCodeInfo"</v>
                              <v n="Type">"CODE.ST_CodeInfo"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">283L</v>
                            </o>
                            <v n="Id">282L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>sFullCode</v>
                            <v>eCodeType</v>
                            <v>stCodeInfo</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>T_MaxString</v>
                            <v>E_CodeAI</v>
                            <v>ST_CodeInfo</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>F_GetItemAI</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>T_MaxString</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">Function</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">277L</v>
                      </o>
                      <v n="Id">285L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">81L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">242L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Action Name="InitManual" Id="{82e374ac-3a1c-4ce3-97a1-fb1ecbadc4a3}">
      <Implementation>
        <ST><![CDATA[
sFullCode	:= '(01)17501031711052(21)86174He081137058500(240)10108245(10)86352024(91)5304012';
stCodeInfo.eCodeType	:= CODE.E_CodeType.E_CASE;

	
//eCodeType	:= CODE.E_CodeAI.GTIN;
eCodeType	:= CODE.E_CodeAI.SERIAL;
//eCodeType	:= CODE.E_CodeAI.RSKU;
//eCodeType	:= CODE.E_CodeAI.BATCH;
//eCodeType	:= CODE.E_CodeAI.PO;


// GTIN 
	stCodeInfo.stGTIN.sStartAI := '(01)';
	stCodeInfo.stGTIN.sEndAI := '(';
	stCodeInfo.stGTIN.nCodeLength := 14;
	stCodeInfo.stGTIN.nCodeStartPos := 0;	
	
// SERIAL	
	stCodeInfo.stSerialCode.sStartAI := '(21)';
	stCodeInfo.stSerialCode.sEndAI := '(';
	stCodeInfo.stSerialCode.nCodeLength := 19;
	stCodeInfo.stSerialCode.nCodeStartPos := 0;	
	
// RSKU
	stCodeInfo.stRSKU.sStartAI := '(240)';
	stCodeInfo.stRSKU.sEndAI := '(';
	stCodeInfo.stRSKU.nCodeLength := 8;
	stCodeInfo.stRSKU.nCodeStartPos := 0;	
	
// BATCH
	stCodeInfo.stBatchID.sStartAI := '(10)';
	stCodeInfo.stBatchID.sEndAI := '(';
	stCodeInfo.stBatchID.nCodeLength := 8;
	stCodeInfo.stBatchID.nCodeStartPos := 0;	
	
// PRODUCTION ORDER
	stCodeInfo.stProductionOrder.sStartAI := '(91)';
	stCodeInfo.stProductionOrder.sEndAI := '(';
	stCodeInfo.stProductionOrder.nCodeLength := 7;
	stCodeInfo.stProductionOrder.nCodeStartPos := 0;	



stCodeInfo.nMinLength 		:= 10;
stCodeInfo.nEntireLength	:= 77;
stCodeInfo.nNumberOfAIs		:= 5;
]]></ST>
      </Implementation>
    </Action>
  </POU>
</TcPlcObject>